vim.g.mapleader = ' '

vim.api.nvim_set_keymap('n', '<c-s>', ':w<CR>', {})
vim.api.nvim_set_keymap('n', ';', ':', {})
vim.api.nvim_set_keymap('i', '<c-j>', 'copilot#Accept("\\<CR>")', { silent = true, script = true, expr = true })
vim.api.nvim_set_keymap('i', '<c-s>', '<ESC>:w<CR>a', {})
vim.api.nvim_set_keymap('i', '<c-p>', '<up>', { noremap = true, silent = true, nowait = true })
vim.api.nvim_set_keymap('i', '<c-n>', '<down>', { noremap = true, silent = true, nowait = true })
vim.api.nvim_set_keymap('i', '<c-b>', '<left>', { noremap = true, silent = true, nowait = true })
vim.api.nvim_set_keymap('i', '<c-f>', '<right>', { noremap = true, silent = true, nowait = true })
vim.api.nvim_set_keymap('i', '<c-k>', '<C-o>D', { noremap = true, silent = true, nowait = true })
vim.api.nvim_set_keymap('n', '<leader>n', '<cmd>NvimTreeToggle<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>r', '<cmd>Telescope live_grep<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>f', '<cmd>Telescope find_files prompt_prefix=🔍 <CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-r>', '<cmd>Telescope<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-x>', '<cmd>Telescope<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '-', '$', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>s', '<cmd>FloatermToggle <CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>g', '<cmd>FloatermNew --width=0.8 --height=0.8 lazygit<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<space>/', '<cmd>Commentary<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<space>/', '<cmd>Commentary<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('t', '<esc>', '<C-\\><C-n>', { silent = true })
vim.api.nvim_set_keymap('n', 'H', '<cmd>vertical resize+10<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'J', '<cmd>resize-10<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'K', '<cmd>resize+10<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'L', '<cmd>vertical resize-10<CR>', { noremap = true, silent = true })
